server:
  port: 9000
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false