spring:
  application:
    name: gateWay
  cloud:
    nacos:
      server-addr: 47.95.122.17:8848
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/getUser/**,/listUsers
        - id: orderService
          uri: lb://orderService
          predicates:
            - Path=/getOrder/**,/listOrders
            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
          filters:
            - AddRequestHeader=X-Request-red, blue
      default-filters:
        - AddRequestHeader=X-Request-red, red
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

server:
  port: 8888
