server:
  port: 9001
spring:
  application:
    name: userService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.122.17:3306/cloud_user?useSSL=false
    username: root
    password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
    fetch-registry: true #是否从eureka server 中获取注册的服务信息
logging:
  level:
    com.zjipst: debug