server:
  port: 9002
spring:
  application:
    name: orderService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.122.17:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 47.95.122.17:8848
      discovery:
        cluster-name: HZ
#        namespace: 48f33eab-c187-4b96-a090-fd337b57c00a
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
#    fetch-registry: true #是否从eureka server 中获取注册的服务信息
mybatis:
  type-aliases-package: com.zjipst.order.entity
  configuration:
    map-underscore-to-camel-case: true  #定义mybatis的映射关系 eg:a_xm -> aXm
userService:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    clients:
      - userService
    enabled: true
#feign:
#  client:
#    config:
#      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
#        loggerLevel: BASIC #  日志级别
logging:
  level:
    com.zjipst: debug
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50 #每个路径的最大连接数