server:
  port: 9002
spring:
  application:
    name: orderService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.122.17:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
    fetch-registry: true #是否从eureka server 中获取注册的服务信息